[package]
name = "tldr"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.8.0"
serde = { version = "1.0.131", features = ["derive"] }
serde_json = "1.0.73"
timed = "0.2.1"
